### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by PixelatedLagg** [dekrypted/simple-ip-grabber#1]
You realise anyone visiting this website can see the webhook URL.

**Comment by dekrypted** [comment]
Yes, hence the name: "Simple IP Grabber"
This is not intended to be used for anything really, just a base code.

I also made this forever and a half ago when I barely knew how to code, so if you're looking for a decent IP grabber consider checking out my [Image IP Grabber](https://github.com/dekrypted/discord-image-logger)

Probably gonna delete all my shit repo's soon so yeah.
